- hosts: all
  become: yes
  tasks:
  - name: install epel-release
    yum:
      name: epel-release
      state: present
      update_cache: true
  - name: install base tools
    yum:
      name:
        - openvpn
        - iperf3
      state: present
      update_cache: true
  - name: setenforce 0 
    selinux:
      state: disabled
- hosts: server
  become: yes
  tasks:
  - name: Copy conf
    template: 
      src: server.conf.j2
      dest: /etc/openvpn/server.conf
      owner: root
      group: root
      mode: 0640
  - name: Copy secret
    template: 
      src: secret
      dest: /etc/openvpn/static.key
      owner: root 
      group: root 
      mode: 0600
  - name: restart openvpn
    systemd:
      name: openvpn@server
      state: restarted
      enabled: true 
- hosts: client
  become: yes
  tasks:
  - name: Copy conf
    template: 
      src: client.server.conf.j2
      dest: /etc/openvpn/server.conf
      owner: root
      group: root
      mode: 0640
  - name: Copy secret
    template:
      src: secret
      dest: /etc/openvpn/static.key
      owner: root
      group: root
      mode: 0600
  - name: restart openvpn
    systemd:
      name: openvpn@server
      state: restarted
      enabled: true 
- hosts: ras
  become: yes
  tasks:
  - name: install easy-rsa
    yum:
      name: easy-rsa
      state: present
      update_cache: true
  - name: init pki
    shell: "/usr/share/easy-rsa/3.0.8/easyrsa init-pki"
    args:
      chdir: /etc/openvpn/
  - name: generate keys
    shell: "echo 'rasvpn' | /usr/share/easy-rsa/3.0.8/easyrsa build-ca nopass"
    args:
      chdir: /etc/openvpn/
  - name: generate keys
    shell: "echo 'rasvpn' | /usr/share/easy-rsa/3.0.8/easyrsa gen-req server nopass"
    args:
      chdir: /etc/openvpn/
  - name: generate keys
    shell: "echo 'yes' | /usr/share/easy-rsa/3.0.8/easyrsa sign-req server server"
    args:
      chdir: /etc/openvpn/
  - name: generate keys
    shell: "/usr/share/easy-rsa/3.0.8/easyrsa gen-dh"
    args:
      chdir: /etc/openvpn/
  - name: generate keys
    shell: "openvpn --genkey --secret ta.key"
    args:
      chdir: /etc/openvpn/
  - name: generate client keys
    shell: "echo 'client' | /usr/share/easy-rsa/3/easyrsa gen-req client nopass"
    args:
      chdir: /etc/openvpn/
  - name: generate client keys
    shell: "echo 'yes' | /usr/share/easy-rsa/3/easyrsa sign-req client client"
    args:
      chdir: /etc/openvpn/
  - name: Copy server.conf
    template:
      src: rasserver.conf.j2
      dest: /etc/openvpn/server.conf
      owner: root
      group: root
      mode: 0600
  - name: add route
    shell: echo 'iroute 192.168.20.0 255.255.255.0' > /etc/openvpn/client/client
  - name: fetch ca.crt
    fetch:
      src: /etc/openvpn/pki/ca.crt
      dest: ca.crt
      flat: yes
  - name: fetch client.crt
    fetch:
      src: /etc/openvpn/pki/issued/client.crt
      dest: client.crt
      flat: yes
  - name: fetch client.key
    fetch:
      src: /etc/openvpn/pki/private/client.key
      dest: client.key
      flat: yes
  - name: restart openvpn
    systemd:
      name: openvpn@server
      state: restarted
      enabled: true
